version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - ${PORT}:${PORT}
    working_dir: /app
    command: node ./dist/index.js
    environment:
      - PORT=${PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

  redis:
    image: redis:latest
    container_name: redis1
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data
    depends_on:
      - redis

  curl-request:
    image: curlimages/curl:latest
    entrypoint: >
      curl -X POST 'http://redis-insight:5540/api/databases'
      -H 'Accept: application/json, text/plain, */*'
      -H 'Connection: keep-alive'
      -H 'Content-Type: application/json'
      --data-raw '{"name":"redis-alias","host":"${REDIS_HOST}","port":${REDIS_PORT},"db":0,"compressor":"NONE","timeout":30000,"ssh":false,"tls":false}'
    depends_on:
      - redis-insight
      - redis
    restart: "on-failure"

volumes:
  redis_volume_data:
  redis-insight:
