version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    working_dir: /app
    command: node ./dist/index.js
    environment:
      - PORT=3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis1
    restart: always
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_insight
    restart: always
    ports:
      - 8001:8001
    volumes:
      - redis_insight_volume_data:/db

volumes:
  redis_volume_data:
  redis_insight_volume_data: